resources:
- repo: self
trigger: none
pr: none

variables:
- template: templates/vars.yml

parameters:
  - name: selectedPackage
    displayName: 'Package for publish (projectName -> packageName)'
    type: string
    default: 'none'
    values:
      - 'none'
      - 'ZendeskCoreSDK.Bindings -> Softeq.ZendeskCoreSDK.iOS'
      - 'SDKConfigurations.Bindings -> Softeq.ZendeskSDKConfigurationsSDK.iOS'
      - 'CommonUISDK.Bindings -> Softeq.ZendeskCommonUISDK.iOS'
      - 'MessagingAPI.Bindings -> Softeq.ZendeskMessagingAPISDK.iOS'
      - 'MessagingSDK.Bindings -> Softeq.ZendeskMessagingSDK.iOS'
      - 'SupportProvidersSDK.Bindings -> Softeq.ZendeskSupportProvidersSDK.iOS'
      - 'SupportSDK.Bindings -> Softeq.ZendeskSupportSDK.iOS'
      - 'ChatProvidersSDK.Bindings -> Softeq.ZendeskChatProvidersSDK.iOS'
      - 'ChatSDK.Bindings -> Softeq.ZendeskChatSDK.iOS'

jobs:
- job: macOS
  pool:
    vmImage: $(MACOS_VM_IMAGE)
  steps:
  - bash: |
      echo ${{ parameters.selectedPackage }}
      IFS=' -> ' read -ra ARR <<< "${{ parameters.selectedPackage }}"; # split parameter value

      PROJECT_NAME=${ARR[0]}
      echo "Run for project: $PROJECT_NAME"
      echo "##vso[task.setvariable variable=projectName]$PROJECT_NAME"

      PACKAGE_NAME=${ARR[2]}
      echo "Package for publish: $PACKAGE_NAME"
      echo "##vso[task.setvariable variable=packageName]$PACKAGE_NAME"
    displayName: 'Set build variables'

  - template: templates/setup-dotnet.yml
    parameters:
      version: $(DOTNET_SDK_VERSION)

  - template: templates/setup-xcode.yml
    parameters:
      version: $(XCODE_VERSION)

  - task: Bash@3
    displayName: Pack Library
    inputs:
      targetType: 'inline'
      script: |
        cd $(projectName) && dotnet pack -c Release -o .
  - task: CopyFiles@2
    inputs:
      contents: '$(projectName)/$(packageName)*.nupkg'
      targetFolder: $(Build.ArtifactStagingDirectory)
  - task: PublishBuildArtifacts@1
    inputs:
      ArtifactName: 'drop'