resources:
- repo: self
trigger: none

variables:
- template: templates/vars.yml

jobs:
- template: templates/nuget-steps.yml
  parameters:
    ProjectName: 'MessagingAPI.Bindings'
    PackageName: 'Softeq.ZendeskMessagingAPISDK.iOS'